# Пример 1 (Nashpy)

In [1]:
# Если библиотека nashpy не установлена, то нужно выполнить команду
# conda install -c conda-forge nashpy
# или
# pip install nashpy

In [2]:
# Работа с матрицами
import numpy as np
# Для поиска равновесия
import nashpy as nash

Двое играют на деньги, одновременно называя одно из чисел 1 или 2, 
и потом считая сумму $S$. Если $S$ четная, то первый выигрывает у второго $S$ долларов,
если $S$ нечетная, то второй выигрывает у первого $S$ долларов. 

In [3]:
# Pay-off matrix
A = np.array([ [2, -3], [-3, 4] ])
print(A)

[[ 2 -3]
 [-3  4]]


In [4]:
# Задаём игру
zsg = nash.Game(A)
print(zsg)

Zero sum game with payoff matrices:

Row player:
[[ 2 -3]
 [-3  4]]

Column player:
[[-2  3]
 [ 3 -4]]


## Ожидаемый выигрыш
Предположим, что игроки следуют смешанным стратегиям 
\begin{align*}
    P^\top&=\begin{pmatrix} 0.3 & 0.7\end{pmatrix} & 
    Q^\top&=\begin{pmatrix} 0.25 & 0.75\end{pmatrix}.
\end{align*}
Ожидаемый выигрыш каждого из игроков:

- Ожидаемый выигрыш первого $EU_A(P,Q)=P^\top AQ$, 
- Ожидаемый выигрыш второго $EU_B(P,Q)=-EU_A(P,Q)$

In [5]:
P = np.array([0.3, 0.7])
Q = np.array([0.25, 0.75])
# Ожидаемый выигрыш
print(zsg[P,Q])

[ 1.05 -1.05]


## Равновесие Нэша в смешанных стратегиях

In [6]:
nash_eq = zsg.linear_program() # решаем задачи линейного программирования

print('Равновесная смешанная стратегия первого игрока: ', nash_eq[0])
print('Равновесная смешанная стратегия второго игрока: ', nash_eq[1])
print('Выигрыши игроков:', zsg[nash_eq[0], nash_eq[1]])

Равновесная смешанная стратегия первого игрока:  [0.58333333 0.41666667]
Равновесная смешанная стратегия второго игрока:  [0.58333333 0.41666667]
Выигрыши игроков: [-0.08333333  0.08333333]
