# Игра "Камень-ножницы-бумага"
Пусть платёж равен 1

Игра в нормальной форме

||К2|Н2|Б2|
|-|-|-|-|
|K1|0,0|1,-1|-1,1|
|Н1|-1,1|0,0|1,-1|
|Б1|1,-1|-1,1|0,0|

Платёжная матрицы
$$
	A=\begin{pmatrix} 0 & 1 & -1 \\ -1 & 0 & 1 \\ 1 & -1 & 0\end{pmatrix}
$$

In [1]:
import numpy as np
from scipy.optimize import linprog

In [2]:
# платёжная матрица
A = np.array([[0, 1, -1], [-1, 0, 1], [1, -1, 0]])
print(A)

[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]


## Первый игнок

In [3]:
c = np.full(shape=3, fill_value=1)
b = np.full(shape=3, fill_value=-1)

shift = 2

res = linprog(c, A_ub=-A.T-shift, b_ub=b)

# цена игры
value1 = 1/res.fun-shift
# равновесная стратегия
P_star = res.x/res.fun

P_star, value1

(array([0.33333333, 0.33333333, 0.33333333]), 0.0)

## Второй игрок

In [4]:
c = np.full(shape=3, fill_value=-1)
b = np.full(shape=3, fill_value=1)

shift = 4

res = linprog(c, A_ub=A+shift, b_ub=b)

# ожидаемы выигрыш первого = -value1
value2 = 1/res.fun+shift
# равновесная стратегия
Q_star = -res.x/res.fun

Q_star, value2

(array([0.33333333, 0.33333333, 0.33333333]), 0.0)