# Пример 2 (Nashpy)

In [1]:
# Если библиотека nashpy не установлена, то нужно выполнить команду
# conda install -c conda-forge nashpy
# Работа с матрицами
import numpy as np
# Для поиска равновесия
import nashpy as nash

Рассморим игру в нормальной форме с матрицами
\begin{align*}
    A&=\begin{pmatrix} 6 & 4 \\ 8 & 3 \end{pmatrix} &
    B&=\begin{pmatrix} 3 & 5 \\ 3 & 2 \end{pmatrix}
\end{align*}
или в виде таблицы

| | $s_{-1}$ | $s_{-2}$ |
|--|---|---|
|$s_1$| (6,3) | (4,5)|
|$s_2$| (8,3) | (3,2)|

In [2]:
# Pay-off matrices
A = np.array([ [6, 4], [8, 3] ])
B = np.array([ [3, 5], [3, 2] ])
A, B

(array([[6, 4],
        [8, 3]]),
 array([[3, 5],
        [3, 2]]))

In [3]:
# Задаём игру
nzsg = nash.Game(A,B)
print(nzsg)

Bi matrix game with payoff matrices:

Row player:
[[6 4]
 [8 3]]

Column player:
[[3 5]
 [3 2]]


## Ожидаемый выигрыш
Предположим, что игроки следуют смешанным стратегиям 
\begin{align*}
    P^\top&=\begin{pmatrix} 0.7 & 0.3\end{pmatrix} & 
    Q^\top&=\begin{pmatrix} 0.35 & 0.65\end{pmatrix}.
\end{align*}    
Ожидаемый выигрыш каждого из игроков:

- Ожидаемый выигрыш первого $EU_A(P,Q)=P^\top AQ$
- Ожидаемый выигрыш второго $EU_B(P,Q)=P^\top BQ$

In [4]:
P = np.array([0.7, 0.3])
Q = np.array([0.35, 0.65])
print(nzsg[P,Q])

[4.715 3.715]


## Равновесие Нэша в чистых и смешанных стратегиях

In [5]:
nash_eq = nzsg.support_enumeration()

for eq in nash_eq:
    print(eq)
    print(nzsg[eq])

(array([1., 0.]), array([0., 1.]))
[4. 5.]
(array([0., 1.]), array([1., 0.]))
[8. 3.]
(array([0.33333333, 0.66666667]), array([0.33333333, 0.66666667]))
[4.66666667 3.        ]
