In [ ]:
import numpy as np
from scipy.optimize import linprog

## Первый игнок

In [ ]:
c = np.array([-1, -1, -1])

b = np.array([1, 1, 1])

A = np.array([[5, 4, 6], [6, 5, 4], [4, 6, 5]])

res = linprog(c, A_ub=A, b_ub=b)

res

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -0.2
              x: [ 6.667e-02  6.667e-02  6.667e-02]
            nit: 3
          lower:  residual: [ 6.667e-02  6.667e-02  6.667e-02]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00  0.000e+00]
                 marginals: [-6.667e-02 -6.667e-02 -6.667e-02]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0

In [ ]:
res.x

array([0.06666667, 0.06666667, 0.06666667])

In [ ]:
res.fun

-0.2

In [ ]:
# вероятости первого игрока
-res.x/res.fun

array([0.33333333, 0.33333333, 0.33333333])

In [ ]:
#  Цена игры
-1/res.fun-5

0.0

## Второй игрок

In [ ]:
c = np.array([1, 1, 1])

b = np.array([-1, -1, -1])

A = -np.array([[5, 6, 4], [4, 5, 6], [6, 4, 5]])

res = linprog(c, A_ub=A, b_ub=b)

res

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 0.2
              x: [ 6.667e-02  6.667e-02  6.667e-02]
            nit: 3
          lower:  residual: [ 6.667e-02  6.667e-02  6.667e-02]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00  0.000e+00]
                 marginals: [-6.667e-02 -6.667e-02 -6.667e-02]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0

In [ ]:
# вероятости первого игрока
res.x/res.fun

array([0.33333333, 0.33333333, 0.33333333])

In [ ]:
#  Цена игры
1/res.fun-5

0.0