# Example 1 (Nashpy)

In [1]:
# If the nashpy library is not installed, run the command
# conda install -c conda-forge nashpy
# or
# pip install nashpy

In [2]:
# Working with matrices
import numpy as np
# For finding equilibria
import nashpy as nash

Two players play for money, simultaneously naming one of the numbers 1 or 2, 
and then calculating the sum $S$. If $S$ is even, then the first player wins $S$ dollars from the second,
if $S$ is odd, then the second wins $S$ dollars from the first. 

In [3]:
# Pay-off matrix
A = np.array([ [2, -3], [-3, 4] ])
print(A)

[[ 2 -3]
 [-3  4]]


In [4]:
# Define the game
zsg = nash.Game(A)
print(zsg)

Zero sum game with payoff matrices:

Row player:
[[ 2 -3]
 [-3  4]]

Column player:
[[-2  3]
 [ 3 -4]]


## Expected Payoff
Suppose players follow mixed strategies 
\begin{align*}
    P^\top&=\begin{pmatrix} 0.3 & 0.7\end{pmatrix} & 
    Q^\top&=\begin{pmatrix} 0.25 & 0.75\end{pmatrix}.
\end{align*}
Expected payoff for each player:

- Expected payoff of the first player $EU_A(P,Q)=P^\top AQ$, 
- Expected payoff of the second player $EU_B(P,Q)=-EU_A(P,Q)$

In [5]:
P = np.array([0.3, 0.7])
Q = np.array([0.25, 0.75])
# Expected payoff
print(zsg[P,Q])

[ 1.05 -1.05]


## Nash Equilibrium in Mixed Strategies

### method `.linear_program()`

In [6]:
nash_eq = zsg.linear_program() # solve linear programming problems

print('Equilibrium mixed strategy of the first player: ', nash_eq[0])
print('Equilibrium mixed strategy of the second player: ', nash_eq[1])
print('Player payoffs:', zsg[nash_eq[0], nash_eq[1]])

Equilibrium mixed strategy of the first player:  [0.58333333 0.41666667]
Equilibrium mixed strategy of the second player:  [0.58333333 0.41666667]
Player payoffs: [-0.08333333  0.08333333]


### method `.support_enumeration()`

In [7]:
nash_eq = zsg.support_enumeration()

for eq in nash_eq:
	print('Equilibrium mixed strategy of the first player: ', eq[0])
	print('Equilibrium mixed strategy of the second player: ', eq[1])
	print('Player payoffs: ', zsg[eq])

Equilibrium mixed strategy of the first player:  [0.58333333 0.41666667]
Equilibrium mixed strategy of the second player:  [0.58333333 0.41666667]
Player payoffs:  [-0.08333333  0.08333333]
