# Game "Rock-Paper-Scissors"
Let the payoff be 1

Game in normal form

||R2|P2|S2|
|-|-|-|-|
|R1|0,0|1,-1|-1,1|
|P1|-1,1|0,0|1,-1|
|S1|1,-1|-1,1|0,0|

Payoff matrix
$$
	A=\begin{pmatrix} 0 & 1 & -1 \\ -1 & 0 & 1 \\ 1 & -1 & 0\end{pmatrix}
$$

In [1]:
import numpy as np
from scipy.optimize import linprog

In [2]:
# payoff matrix
A = np.array([[0, 1, -1], [-1, 0, 1], [1, -1, 0]])
print(A)

[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]


## First player

In [3]:
c = np.full(shape=3, fill_value=1)
b = np.full(shape=3, fill_value=-1)

shift = 2

res = linprog(c, A_ub=-A.T-shift, b_ub=b)

# value of the game
value1 = 1/res.fun-shift
# equilibrium strategy
P_star = res.x/res.fun

P_star, value1

(array([0.33333333, 0.33333333, 0.33333333]), 0.0)

## Second player

In [4]:
c = np.full(shape=3, fill_value=-1)
b = np.full(shape=3, fill_value=1)

shift = 4

res = linprog(c, A_ub=A+shift, b_ub=b)

# expected payoff of the first = -value1
value2 = 1/res.fun+shift
# equilibrium strategy
Q_star = -res.x/res.fun

Q_star, value2

(array([0.33333333, 0.33333333, 0.33333333]), 0.0)